function chars = characters_catalog()
  %char
  # chars(i) = Character(nome, classe, nex, ...
                        %trail, origin, ...
                        %atr, [for,agi,int,vig,pre] ...
                        %skl  {"skl1", "skl2"}); i++
  i = 1;
  chars(i) = Character("Augusto Blanco", "Ocultista", 10, ...
                       "Lâmina Paranormal", "Militar", ...
                       [1, 2, 3, 1, 2], ...
                       {"Tiro Preciso", "Resistência"}); i++;

  chars(i) = Character("Lee Papa Bushiro", "Combatente", 20, ...
                       "Guerreiro", "Policial", ...
                       [2, 3, 1, 2, 1], ...
                       {"Ritualizar", "Explosão Sensorial"}); i++;

  chars(i) = Character("Lucas Vásquez", "Especialista", 15, ...
                       "Atirador de Elite", "Mercenário", ...
                       [1, 3, 2, 1, 2], ...
                       {"Arrombamento", "Filho Da Puta"}); i++;

  chars(i) = Character("Isabelle Bennett", "Ocultista", 15, ...
                       "Graduada", "Universitária", ...
                       [1, 2, 3, 1, 2], ...
                       {"Foda-se", "Porra"}); i++;

  chars(i) = Character("Samuel Ridrogues", "Combatente", 15, ...
                       "Atirador de Elite", "Mercenário", ...
                       [1, 3, 2, 1, 2], ...
                       {"Disgraça", "Pelada"}); i++;

  chars(i) = Character("Kaito Marston", "Combatente", 15, ...
                       "Tropa de Choque", "Desgarrado", ...
                       [2, 1, 1, 3, 2], ...
                       {"marsto", "kaito"}); i++;
end

